
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ReleaseManagementAssignment
{

using System;
    using System.Collections.Generic;
    
public partial class Module
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Module()
    {

        this.developers = new HashSet<developer>();

        this.testers = new HashSet<tester>();

    }


    public int module_id { get; set; }

    public Nullable<System.DateTime> expected_start_date { get; set; }

    public Nullable<System.DateTime> expected_end_date { get; set; }

    public Nullable<System.DateTime> actual_start_date { get; set; }

    public Nullable<System.DateTime> actual_end_date { get; set; }

    public Nullable<int> pid { get; set; }



    public virtual Project1 Project { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<developer> developers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tester> testers { get; set; }

}

}
