
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ReleaseManagementAssignment
{

using System;
    using System.Collections.Generic;
    
public partial class Project1
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Project1()
    {

        this.ProjectLists = new HashSet<ProjectList>();

        this.Modules = new HashSet<Module>();

    }


    public int ProId { get; set; }

    public string ProName { get; set; }

    public Nullable<System.DateTime> Actual_End_Date { get; set; }

    public Nullable<System.DateTime> Actual_Start_Date { get; set; }

    public Nullable<System.DateTime> Expected_Start_Date { get; set; }

    public Nullable<System.DateTime> Expected_End_Date { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProjectList> ProjectLists { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Module> Modules { get; set; }

}

}
