
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ReleaseManagementAssignment
{

using System;
    using System.Collections.Generic;
    
public partial class Team
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Team()
    {

        this.EmpTeams = new HashSet<EmpTeam>();

    }


    public int TeamId { get; set; }

    public int TeamLeadId { get; set; }

    public string LeadName { get; set; }



    public virtual EmployeeList EmployeeList { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmpTeam> EmpTeams { get; set; }

}

}
