
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ReleaseManagementAssignment
{

using System;
    using System.Collections.Generic;
    
public partial class tester
{

    public Nullable<int> tester_id { get; set; }

    public Nullable<int> module_id { get; set; }

    public Nullable<int> r_status { get; set; }

    public int Sno { get; set; }



    public virtual EmployeeList EmployeeList { get; set; }

    public virtual Module Module { get; set; }

}

}
